name = "YaoZX"
uuid = "e9678f2b-e210-420c-b40d-e148dd84e1f3"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "0.1.0"

[deps]
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"
ZXCalculus = "3525faa3-032d-4235-a8d4-8c2939a218dd"

[compat]
julia = "1"
YaoBlocks = 0.11
ZXCalculus = 0.1

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoExtensions = "7a06699c-c960-11e9-3c98-9f78548b5f0f"

[targets]
test = ["Test", "Yao", "YaoExtensions"]
